"""cascade

Revision ID: 75ef26f14573
Revises: e8bcd9de572f
Create Date: 2026-01-04 11:27:26.706138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ef26f14573'
down_revision: Union[str, Sequence[str], None] = 'e8bcd9de572f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_tag_task_id_fkey'), 'task_tag', type_='foreignkey')
    op.drop_constraint(op.f('task_tag_tag_id_fkey'), 'task_tag', type_='foreignkey')
    op.create_foreign_key(None, 'task_tag', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_tag', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'task_tag', type_='foreignkey')
    op.drop_constraint(None, 'task_tag', type_='foreignkey')
    op.create_foreign_key(op.f('task_tag_tag_id_fkey'), 'task_tag', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('task_tag_task_id_fkey'), 'task_tag', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    # ### end Alembic commands ###
